# Generated by Django 4.2.4 on 2023-08-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assetList', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.assetlist')),
            ],
        ),
    ]
