# Generated by Django 4.2.4 on 2023-08-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_histprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistPrice',
            new_name='HistoricalPrice',
        ),
    ]
